name: Run Selenium Automation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Remove default Chrome and install Chrome 123
        run: |
          sudo apt-get remove google-chrome-stable -y || true
          wget https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux/x64/google-chrome-stable_123.0.6312.86-1_amd64.deb
          sudo dpkg -i google-chrome-stable_123.0.6312.86-1_amd64.deb || sudo apt-get -f install -y

      - name: Verify Chrome version
        run: |
          google-chrome --version
          chromedriver --version || true

      - name: Run Tests with Maven
        run: mvn clean test -DsuiteXmlFile=src/resources/testng.xml
